default_region = "eu-central-1"
secondary_region = "us-east-1"
env = "dev"
repo_name = "dev/irezd/fastapi"
ecs_service_name = "dev-fastapi-service"
fqdn = "test.fastapi.dennisowie.com"
capacity_provider_name = "CustomEC2Provider"